name: lua ca bouncer nginx test

on:
  push:
    branches:
      - main
      - releases/**
  pull_request:
    branches:
      - main
      - releases/**


jobs:
  tests:
    runs-on: ubuntu-latest
    name: "Nginx test suite"
    container:
      image: nginx:stable-bookworm-perl

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: false
    - name: "install nginx & nginx perl test suite"
      run: |
        cat /etc/os-release
        apt-get update
        apt-get install -y make gcc
        cpan Test::Nginx
    - name: "run tests"
      run: |
        cat /etc/os-release
        for i in t/*.t; do
           prove $i ;
        done
